require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/content_security_policy.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
