require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/content_security_policy.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'lib/generators/api_controller_generator.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - 'lib/generators/api_controller_generator.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/*'

Rspec/ExampleLength:
  Enabled: false

Rspec/ExpectChange:
  Enabled: false
