---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/{api_uuid}/pets":
    get:
      summary: pets#index
      tags:
      - pets
      parameters:
      - name: api_uuid
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
    post:
      summary: pets#create
      tags:
      - pets
      parameters:
      - name: api_uuid
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/{api_uuid}/pets/{uuid}":
    get:
      summary: pets#show
      tags:
      - pets
      parameters:
      - name: api_uuid
        in: path
        required: true
        schema:
          type: string
      - name: uuid
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
    patch:
      summary: pets#update
      tags:
      - pets
      parameters:
      - name: api_uuid
        in: path
        required: true
        schema:
          type: string
      - name: uuid
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: succes
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: pets#destroy
      tags:
      - pets
      parameters:
      - name: api_uuid
        in: path
        required: true
        schema:
          type: string
      - name: uuid
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: succes
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
