default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_tools_development
test:
  <<: *default
  database: api_tools_test
production:
  <<: *default
  database: api_tools_production
  username: api_tools
  password: <%= ENV["API_TOOLS_DATABASE_PASSWORD"] %>
